version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    container_name: web
    volumes:
      - /usr/src/node_modules
      - .:/usr/src/app
    command: yarn dev
    ports:
      - "3000:3000"

  # mysql:
  #   image: mysql:5.7
  #   env_file: ./.env