version: '3'
services:
  mysql:
    image: mysql:8.0.29
    platform: linux/x86_64
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: reversi
      MYSQL_USER: reversi
      MYSQL_PASSWORD: password

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: api
    ports:
      - "8000:8000"  # APIは8000ポートでリッスン
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: reversi
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: reversi
    depends_on:
      - mysql
    volumes:
      - ./src:/app/src

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - api
